### ISSUE TITLE
master vs. gh-pages 

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#108]
@matallo I was doing a quick typo fix and was about to merge master into gh-pages, but noticed all the files in `_site/`, so didn't move forward. 

![screen shot 2015-01-03 at 17 37 29](https://cloud.githubusercontent.com/assets/1041056/5604003/7371fe7e-936f-11e4-94ed-6fd134abc4a4.png)

I'm guessing these are the website pages generated by jekyll? should these be version controlled?

**Comment by matallo** [comment]
for some reason `.gitignore` in `master` and `gh-pages` was different (and not excluding `_site` in `gh-pages`)

having `_site` around in your `master` branch then checking-out to `gh-pages` would have tried to commit it

updated the `.gitignore` so it won't happen
