### ISSUE TITLE
make multiple links more apparent for better UX

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/academy#122]
When linking to multiple external resources make it apparent that there multiple links instead of [stating](#) [them](#) [like](#) [this](#). It's difficult to tell that there are multiple links this way.

For example:
![academy-bad-link-ux](https://cloud.githubusercontent.com/assets/161748/6431145/49e978c8-bff4-11e4-9dde-a2c0db6b60d8.jpg)

**Comment by ohasselblad** [comment]
thanks :) PR will be merged soon!

**Comment by clhenrick** [comment]
:+1:
