### ISSUE TITLE
Beginner course needs to be updated.

### ISSUE THREAD

**Issue by bfrazarlou** [CartoDB/academy#130]
The Beginner course needs to be updated to reflect the current web application.

In Lesson 1:
  *  There are many more data tables available and the Populated Places layer is harder to find than implied by the tutorial; this is already noted in a separate bug.
  *  There is no longer a plus sign to the right of each layer; you just need to click the name to add it.
  *  The view toggle now says "DATA VIEW" rather than "Table" as described in the tutorial multiple places.
  *  The selection and arrangement of basemaps is different.  
  *  Google Maps basemaps are no longer available.

In Lesson 2:
  *  Same issue with "Table" vs. "Data View", again multiple places in the lesson.
  *  There is no longer a button or link labeled "New table"; there is only the "+" button.
  *  The Add Layer/Create Table dialog looks significantly different.

(There are probably more issues in later lessons, but I'll stop where I'm at.)

**Comment by ohasselblad** [comment]
thanks :) PR to be merged soon.
