### ISSUE TITLE
Academy Lesson 2 outdated with reference to "Visualization Wizard." 

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/academy#142]
Lesson 2, Lesson 4. The language in the below paragraph references the "Simple Visualization Wizard," which is now called the "map layer wizard." 
And then the map shot below it references the same. 

![screen shot 2015-04-14 at 10 57 12 am](https://cloud.githubusercontent.com/assets/938865/7139579/135ad31a-e295-11e4-810b-fff7ae4c199e.png)

**Comment by ohasselblad** [comment]
thanks!
