### ISSUE TITLE
styles for academy maps

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#152]
For academy lessons on cartodb.js, I've been using styles from other sources. Could someone in design take a look at some of the UI elements I've been using and make them look nicer, CartoDB-y?

Example [code here](https://github.com/CartoDB/academy/blob/master/t/03-cartodbjs-ground-up/lesson-4/bonus.html) with [live version here](http://academy.cartodb.com/t/03-cartodbjs-ground-up/lesson-4/bonus.html). There are several other examples in other lessons that use the same styles for the selectors.

**Comment by ohasselblad** [comment]
All of the templates are here: https://github.com/CartoDB/academy/tree/master/t/03-cartodbjs-ground-up

**Comment by carlostallon** [comment]
duplicated
