### ISSUE TITLE
inventory videos and screenshots that have old interfaces

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#161]
The following tutorials and academy lessons have older interfaces:
Tutorials are here: http://docs.cartodb.com/tutorials.html
Academy lessons are here: http://academy.cartodb.com
- [ ] http://docs.cartodb.com/tutorials/simple_points_map.html
- [ ] http://docs.cartodb.com/tutorials/sharing_maps.html
- [ ] ...

(check if they have been updated)

**Comment by ohasselblad** [comment]
@Hayleyr you can inventory it here

**Comment by Hayleyr** [comment]
@ohasselblad but i think they were supposed to be assigned three different categories, not just "old" or not
