### ISSUE TITLE
update design elements in academy cartodb.js examples

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#164]
some of my examples in academy need some design love. we would probably also benefit from a simple style sheet that could be applied to all of the lessons...

examples:

1. https://github.com/CartoDB/academy/blob/master/t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-toggles-and-slider.html ([live version](http://academy.cartodb.com/t/03-cartodbjs-ground-up/lesson-2/CartoDB-js-lesson2-toggles-and-slider.html))
2. https://github.com/CartoDB/academy/blob/master/t/03-cartodbjs-ground-up/lesson-3/cartocss-and-sql.html ([live version](http://academy.cartodb.com/t/03-cartodbjs-ground-up/lesson-3/cartocss-and-sql.html))
3. https://github.com/CartoDB/academy/blob/master/t/03-cartodbjs-ground-up/lesson-4/bonus.html ([live version](http://academy.cartodb.com/t/03-cartodbjs-ground-up/lesson-4/bonus.html))

**Comment by carlostallon** [comment]
@ohasselblad do you think this issue still applies?

**Comment by ohasselblad** [comment]
duplicated in https://github.com/CartoDB/academy/issues/374
