### ISSUE TITLE
Update screenshots for new modals

### ISSUE THREAD

**Issue by viddo** [CartoDB/academy#176]
The screenshots for modals as seen on http://docs.cartodb.com/ are now outdated, so would need to be updated to reflect the [new modals](https://github.com/CartoDB/cartodb-management/wiki/New-Editor#1-modals), that was released on July 23rd.

lessons:
- [ ] http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-1.html#vizjson-nice-to-meet-you

**Comment by ohasselblad** [comment]
thanks @viddo :+1:
