### ISSUE TITLE
only populate sidebar navigator with h3 headers

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#182]
Right now all header levels are showing up in the sidebar. We want to only have h3 levels show up. That is, we don't want h4, h5, etc. to show.

@matallo could you tackle this one in the next week or two?

cc @ztephm

**Comment by ohasselblad** [comment]
@matallo could we get some help with this one this week?

**Comment by piensaenpixel** [comment]
@ohasselblad i can help you this week

**Comment by ohasselblad** [comment]
Great, thanks so much @piensaenpixel :)

**Comment by ohasselblad** [comment]
hey @piensaenpixel is there anything you need from us on this?
