### ISSUE TITLE
Make Map Academy Responsive

### ISSUE THREAD

**Issue by ztephm** [CartoDB/academy#188]
Can we make Academy pages responsive so that when users view on smaller resolution screens they are seeing "our courses" green blocks stack in a way where they only have to scroll vertically?

Currently they have to scroll horizontally:
![screen shot 2015-08-12 at 12 43 39 pm](https://cloud.githubusercontent.com/assets/1779444/9230396/0c8036c0-40f0-11e5-89dc-934a3a643f83.png)

**Comment by piensaenpixel** [comment]
sure @ztephm
