### ISSUE TITLE
Create Subsections for "Our Courses" Academy section

### ISSUE THREAD

**Issue by ztephm** [CartoDB/academy#189]
cc @ohasselblad 
related: https://github.com/CartoDB/academy/issues/187

Right now to browse courses users have to read course titles in green blocks. It's not immediately apparent which courses are related or which are more advanced than others.

Can we create subsections that organize the courses into groups? We could group them by Beginner / Intermediate / Advanced 
OR 
by series, for example Design Series would include Introduction to Map Design and Intermediate Map Design.

**Comment by ztephm** [comment]
cc @ohasselblad 

ok to make Beginner / Intermed / Advanced horizontal sections,
and make Series (like Design) vertical sections ?

**Comment by carlostallon** [comment]
not apply anymore with the new IA, closing
