### ISSUE TITLE
"Start course" button showing as broken for small screens in Firefox

### ISSUE THREAD

**Issue by iriberri** [CartoDB/academy#197]
Browser: Firefox 40.0.3 (last version)

This behaviour doesn't happen in Chrome neither Safari.

For windows of ~1100 pixels or less the "Start course" button is cut: 

![image](https://cloud.githubusercontent.com/assets/1730320/9579293/d0c215ac-4ff1-11e5-92cd-8b86b3bdbdcb.png)

**Comment by ohasselblad** [comment]
dup of https://github.com/CartoDB/academy/issues/181

**Comment by iriberri** [comment]
Oh, thanks! I actually remembered to have seen the issue previously but I didn't work too hard to find it ;)
