### ISSUE TITLE
level 1 headers not displaying as header

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#200]
<img width="744" alt="screen shot 2015-09-01 at 11 29 34" src="https://cloud.githubusercontent.com/assets/1041056/9608507/c60f3468-509c-11e5-92d3-b502b844f905.png">

**Comment by ohasselblad** [comment]
the issue can be seen in the branch being merged in #201

**Comment by piensaenpixel** [comment]
thanks @ohasselblad :) i'll take care

**Comment by piensaenpixel** [comment]
fixed
