### ISSUE TITLE
create cards and bios for community lessons which are hosted off-site

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#231]
Instead of curating and hosting community lessons on-site, we will instead create an abstract + bio for each lesson. Advice on how to structure this would be very much appreciated!

**Comment by matallo** [comment]
@carlostallon can you take care of this?

**Comment by carlostallon** [comment]
sure. When do you need it @ohasselblad?

**Comment by ohasselblad** [comment]
Just bundled in with the rest of the updates

**Comment by carlostallon** [comment]
:+1:

**Comment by ohasselblad** [comment]
done done done: http://academy.cartodb.com/courses/community/
