### ISSUE TITLE
Minor error in Custom Interactivity tutorial on docs.cartodb.com

### ISSUE THREAD

**Issue by gtallen1187** [CartoDB/academy#239]
In the [Custom Interactivity tutorial](http://docs.cartodb.com/tutorials/custom_interactivity/) from docs.cartodb.com, you provide a [code sample](http://docs.cartodb.com/tutorials/custom_interactivity/#infowindow-templates) for the reader to copy as part of the tutorial.  It looks as though the `cartodb-popup` class has since been upgraded to `cartodb-popup v2`, but the code sample has yet to be updated.  Thought i would flag this now in the hopes of saving others some time down the road.  :grinning: 

 > I spent some time searching to try and find this repository, in the hopes that i could submit a fix myself versus posting an issue, but couldn't find it anywhere.  apologies if i missed it somehow.

**Comment by matallo** [comment]
In that case I'll assign this to @ohasselblad, for him to be on the loop
