### ISSUE TITLE
403 error on Map Academy resources URLs

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/academy#242]
There are some links to datasets on the Map Academy that are not working as expected, returning a 403 error code. 

Some examples: 
  - `http://academy.cartodb.com/d/mississippi_blues_musicians.geojson`
  - `http://academy.cartodb.com/d/highway_61.geojson`
  - `http://academy.cartodb.com/d/all_month.csv.zip`

@matallo please check

**Comment by ohasselblad** [comment]
+1

Failing on this too: http://academy.cartodb.com/d/academy_torque_stork.zip
