### ISSUE TITLE
Advanced Labels tutorial?

### ISSUE THREAD

**Issue by csobier** [CartoDB/academy#263]
I found an old Community email stating that we should create an advanced labels lesson once our [CartoCSS doc](http://docs.cartodb.com/cartodb-platform/cartocss/) is live.  

"Anything regarding color & typography. We should def cover labels in typog. " 
Other request from the same email: 
- labeling features for points, polygons, or lines
- how to work with overlapping labels, or very few labels
- how to rotate text positions for labels 
- On the Product side, add "smart labeling" options?
- Zoom levels in general, zoom in (features are huge), zoom out (too tiny). Too many marker-size rules to fix, is there a better scaling algorithm for zoom features?

We have these CartoCSS properties defined, we just need to put links to these in a collaborative lesson for users. @ohasselblad , up to you if you want to do this. Let me know if you need any input or help!

**Comment by ohasselblad** [comment]
@makella, is this something you would be interested in doing?

**Comment by makella** [comment]
yeah!

**Comment by ohasselblad** [comment]
Cool! Let me know when it fits into your schedule, then we can scope it out together to see how it fits into academy :)
