### ISSUE TITLE
create submission form for map academy community lessons

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#266]
- [x] create form (@ohasselblad)
- [x] get some design love for the form (@carlostallon)
- [x] get feedback on the form (@ohasselblad)
- [x] include it in community course pull request (@ohasselblad)

**Comment by carlostallon** [comment]
Ok Andy! Go go go!

2016-01-14 21:36 GMT+01:00 Andy Eschbacher <notifications@github.com>:

>
>    - create form (@ohasselblad <https://github.com/ohasselblad>)
>    - get some design love for the form (@carlostallon
>    <https://github.com/carlostallon>)
>    - get feedback on the form (@ohasselblad
>    <https://github.com/ohasselblad>)
>    - include it in community course pull request (@ohasselblad
>    <https://github.com/ohasselblad>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/academy/issues/266>.
>



-- 
Carlos Tallón
Designer & Baker

**Comment by ohasselblad** [comment]
ok, ready for you @carlostallon :) I shared with you on gdrive. I took a swing at customizing it, but would love your design eye!

**Comment by ohasselblad** [comment]
woo! thanks @carlostallon!
