### ISSUE TITLE
update academy ux

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#271]
continuance of #259...

- [x] get design review of index.html
- [x] fix layout of tutorial information pages (example [here](http://academy.cartodb.com/courses/community/torque-bird-tracking/) -- i did some rough formatting to make it passable for my webinar, but it could use someone with expertise)
- [x] make sure header is displaying correctly (see overflow issue in screenshot #259)
- [x] new icon for the community section that appears on the main page http://academy.cartodb.com (current icons located in `_app/img/icons`)
- [x] remove 'awesome end of this lesson' for community lesson pages

----
- [ ] code

**Comment by matallo** [comment]
fixed the header issue in https://github.com/CartoDB/academy/pull/276

@carlostallon will be taking over the icon, reassigning then

**Comment by carlostallon** [comment]
Guys, what do you think about this ones. I like the first one:
![new community icon](https://cloud.githubusercontent.com/assets/1712650/12719860/eae9a2f4-c8f7-11e5-9c11-49421c4b1d32.png)

**Comment by ohasselblad** [comment]
I vote for the first one too!

**Comment by carlostallon** [comment]
Just realized that we are already using it for Stack Exchange module, so what about the third one? I like it too...

**Comment by ohasselblad** [comment]
+1 for the third one!

**Comment by carlostallon** [comment]
Guys, a lot of work here to solve some UX problems with Academy pages. The conclusions are that now we have:
- Added search
- Removed difficulty labels from homepage (included inside topics)
- Added Community Tutorials
- Homepage ordered by 6 general topics
- Within each topics we have Courses (sequenced lessons) and Lessons
- Removed the status green bar in lessons
- Layout for Community Lesson fixed
- Icon for community tutorials fixed
- Updated styles to framework 

You can review it here: https://invis.io/NF66CZMVH

**Comment by ohasselblad** [comment]
Nice work :) Need anything from me?

**Comment by carlostallon** [comment]
will be applied in the new design, closing
