### ISSUE TITLE
Update all references of "table" to "datasets"

### ISSUE THREAD

**Issue by csobier** [CartoDB/academy#274]
@ohasselblad , as reported by one of Jeff's clients, the Academy lessons are still using the old terminology of "tables" and "table view", as opposed to "data", "data view", and "datasets". In some cases, there are outdated UI's too. Should do a general clean-up of all lessons.

**Comment by ohasselblad** [comment]
No problemo, thanks! feel free to open a pull request on this. The only difference is that the SQL/PostGIS course should still use 'table', otherwise no problems changing it.
