### ISSUE TITLE
clean up cartodb.js from the ground up lesson 1

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/academy#285]
Format:
1. code examples early on
2. walkthrough of template
3. tl;dr section on viz.json

**Comment by ohasselblad** [comment]
integrate a template for cartodb.js template

**Comment by csobier** [comment]
Fantastic!  You can use [this](https://github.com/CartoDB/cartodb.js/issues/729) as a related resource.  
I can test when ready for review.

**Comment by andy-esch** [comment]
(deprecated)
