### ISSUE TITLE
look into using cartodb yeoman generator for cartodb.js lessons

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#289]
Right now we're using basic boilerplate templates (https://github.com/CartoDB/academy/tree/master/_app/t) for [cartodb.js lessons](http://academy.cartodb.com/courses/cartodbjs-ground-up/)

http://blog.cartodb.com/the-cartodb-yeoman-generator/

upsides:

1. gives users a tool to generate new templates
1. will probably follow current version of cartodb.js?

downsides:

1. another layer of complication for people who may or may not be used to web development
1. may introduce unneed libraries, etc. 

cc/ @nerik

**Comment by nerik** [comment]
> gives users a tool to generate new templates
This will fully make sense when adding more templates. 1st one that comes to mind is an Odyssey one, but I'd love suggestions here.

> will probably follow current version of cartodb.js?
yes

> another layer of complication for people who may or may not be used to web development
Yes, it adds a layer of "black magic" and I know users feel more in control when starting from scratch. This tool is mainly intended for people who already understand the platform

> may introduce unneed libraries, etc.
No, actually, if you don't request extra libraries from the CLI, you will just get cartodb.js
What the generator brings mostly is *tooling* (livereload, server, gist, etc) and best practices (eslint)

**Comment by csobier** [comment]
Yes, just reviewed the blog.  As a novice, I would love to see some consistency between the two basic templates so that it is not confusing to users.

**Comment by ohasselblad** [comment]
Thanks @nerik! I think I'll mention and link to the blog post as another workflow, but don't want to overwhelm noobs by requiring them to use it.

@csobier, which two templates are you referring to? The yeoman one and the basic one in Map Academy?

**Comment by csobier** [comment]
Exactly

**Comment by ohasselblad** [comment]
We won't be doing this, but we'll be linking to @nerik's nice blog post about it.
