### ISSUE TITLE
typo and question about an sql command that doesn't work

### ISSUE THREAD

**Issue by rossbernet** [CartoDB/academy#294]
In this lesson:

http://academy.cartodb.com/courses/sql-postgis/joining-data/

This is a typo (those isos are the same...one should be, 'iso_code' : 
_You’ll see, it doesn’t matter that the columns in the two tables were different, iso versus just, iso_

UPDATE tm_world_borders_s wb
SET big_rivers = (
  SELECT COUNT(table_50m_rivers_lake_cen.cartodb_id)
  FROM table_50m_rivers_lake_cen
  WHERE ST_Intersects(
    wb.the_geom,
    table_50m_rivers_lake_cen.the_geom
  ))

That returned an error for me, but when I got rid of the wb it worked...what happened?

Thanks

**Comment by mehak-sachdeva** [comment]
Thanks for noticing this! We are fixing this at #296
