### ISSUE TITLE
Add how to report errors back to footer

### ISSUE THREAD

**Issue by csobier** [CartoDB/academy#303]
Related to [Docs issue#188](https://github.com/CartoDB/docs/issues/188).  I will see if I can add it back for Academy pages (and for the Docs tutorial pages).

**Comment by matallo** [comment]
actually, we could add an "edit in gihub" link at some point, as in https://mapzen.com/documentation/tangram/ or https://jekyllrb.com/docs/home/

**Comment by ohasselblad** [comment]
I like the idea of having the edit in github, but i don't want to scare users away. we could keep it to simply: "Report an Error or Edit in GitHub".
