### ISSUE TITLE
Adding thumbnail images to courses in Map Academy?

### ISSUE THREAD

**Issue by levie481** [CartoDB/academy#311]
As I've been working on transferring some of our Map Academy courses to other sources (e.g. Discoverspatial.com), I thought maybe it will also be good to add thumbnail images to our courses on Map Academy to make it look like an online course page (many people didn't seem to know we have this free course option on our website and it seems to be a good leading UI element)

Here is for example how they look here: http://discoverspatial.com/courses?query=cartodb 

As a thought! 

(thank you!)

**Comment by ohasselblad** [comment]
cc @carlostallon

**Comment by carlostallon** [comment]
Hey @ohasselblad and @levie481, we will change (not now when) the way we organize courses and lessons in /academy, you can take a look here: https://invis.io/PS78MUERU#/137908497_Academy

It's not planned to add thumbnail to this layout. But I agree that we should be able to highlight this section more to our users.

**Comment by levie481** [comment]
Thank you for sharing the viz, got it - looks great!

**Comment by carlostallon** [comment]
will be improved in the new academy design, closing
