### ISSUE TITLE
Color lesson slider is broken

### ISSUE THREAD

**Issue by ztephm** [CartoDB/academy#324]
cc @ohasselblad  

Hi @matallo can you help us fix the slider at the bottom of [this section](https://academy.cartodb.com/courses/intermediate-design/choose-colors-1/#hue-saturation-and-value) please?

It's an iframe whose contents live in the 't' folder:

![screen shot 2016-06-17 at 7 54 01 pm](https://cloud.githubusercontent.com/assets/1779444/16167620/54e8eb7c-34c5-11e6-97ea-17d56449f4d8.png)

It works properly in [staging](http://academy.cartodb-staging.com/courses/intermediate-design/choose-colors-1/):

![screen shot 2016-06-17 at 7 55 46 pm](https://cloud.githubusercontent.com/assets/1779444/16167643/8514dda6-34c5-11e6-9e88-51ed8f4bcc11.png)

...but we see these errors in live lesson:

![screen shot 2016-06-17 at 7 57 19 pm](https://cloud.githubusercontent.com/assets/1779444/16167660/b9a2ba48-34c5-11e6-9463-2ab626e5d85e.png)

![screen shot 2016-06-17 at 7 57 53 pm](https://cloud.githubusercontent.com/assets/1779444/16167666/d0bffeb6-34c5-11e6-91be-4b247c1fa043.png)

What should we change?

**Comment by ohasselblad** [comment]
fixed in #326
