### ISSUE TITLE
Projections: Create a EPSG:4326 map?

### ISSUE THREAD

**Issue by timrobertson100** [CartoDB/academy#331]
Hey folks,

I'm trying to follow [the instructions on the projection tutorial](https://docs.cartodb.com/tutorials/projections/) to create a map in EPSG:4326 (unprojected WGS84) but it does not seem to work.  The same works for arctic projections for example.

Can anyone point me at an example of how to achieve this please?

Thanks

```
SELECT   
  cartodb_id,
  ST_Transform(the_geom, 4326) AS the_geom_webmercator
FROM 
  world_borders_hd 
```

**Comment by ohasselblad** [comment]
hey @timrobertson100, this query should work as quoted. The difference is that it will be very small and centered on (0, 0). If you go to that point, and zoom into something like zoom 17 or 18, you'll see the mini world borders there. For future questions, please post to http://gis.stackexchange.com/questions/tagged/cartodb and tagging cartodb. cheers!

**Comment by timrobertson100** [comment]
Thanks @ohasselblad 

If anyone stumbles upon this issue, I did ask the question on http://gis.stackexchange.com/questions/200287/creating-a-basemap-in-wgs84
