### ISSUE TITLE
Legend Does Not Get Updated

### ISSUE THREAD

**Issue by Asimov15** [CartoDB/academy#340]
In this tutorial, modifying the CSS does not update the legend.

https://carto.com/docs/tutorials/electoral_map/

**Comment by ohasselblad** [comment]
hi @Asimov15, manually updating the CartoCSS does not change the colors in the legend.

**Comment by ohasselblad** [comment]
hi @Asimov15, yes that is standard behavior for working with custom CartoCSS. If you would like to change the legend, go to the legend panel and change the values there manually. After the CartoCSS is altered, it is very hard to mimic the changes elsewhere so we rely on users to do that. Check out the docs for legends: https://carto.com/docs/carto-editor/maps/#legends
