### ISSUE TITLE
Small images in markdown aren't centering.  

### ISSUE THREAD

**Issue by nygeog** [CartoDB/academy#341]
For when images are a little smaller than the width of the panel, should I use `<img .... >` html styling or do we stick w/ standard markdown `![text](img.png)`, and if so, should I just take wider screen shots?

**Comment by csobier** [comment]
FYI: I was given very strict [image requirements](https://github.com/CartoDB/docs/wiki/Documentation-Markdown-Guide#images) by the Website team, you should do the same.

**Comment by arianaescobar** [comment]
yesss, what she said! ^^^
