### ISSUE TITLE
need new icon for builder?

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#342]
@carlostallon since we're creating a new builder course, we probably need a nice new icon for it too :) What do you think?

**Comment by carlostallon** [comment]
Of course, I will send you today : )

**Comment by carlostallon** [comment]
Here it goes Andy ;)

[builder icon.zip](https://github.com/CartoDB/academy/files/366075/builder.icon.zip)

**Comment by ohasselblad** [comment]
@nygeog here are your new assets for the builder lesson :)

**Comment by csobier** [comment]
Duplicate of Docs icon that was already created- please let's try to use single-sourcing as often as possible :-)

**Comment by carlostallon** [comment]
It's better because they are related, we used also the same icon in SQL or CARTO.js for example.
