### ISSUE TITLE
create cartography cheat sheet

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/academy#348]

**Comment by ohasselblad** [comment]
Resources
* https://carto.com/blog/cartography-data-extract-value/

**Comment by csobier** [comment]
Please note that this may be duplicate content:  https://carto.com/docs/tips-and-tricks/best-practices-checklist/  (Already have a  Docs issue assigned to update this based on Builder content- moving this directly under the Builder topic too).

**Comment by ohasselblad** [comment]
I think what we do here is have cheat sheets for SQL/PostGIS, Carto.js, and Cartography housed in Map Academy, and then link to the Builder one link to the one you linked to :) We could also have the docs version link to the map academy versions. I see the map academy ones being more verbose than the docs ones.
