### ISSUE TITLE
'Unable to display google map element'

### ISSUE THREAD

**Issue by mehak-sachdeva** [CartoDB/academy#360]
This error comes up in the Google Map Driving Directions Visualization lesson:
https://carto.com/academy/courses/cartojs-and-external-apis/google-driving-directions/

**Comment by ohasselblad** [comment]
@michellechandra do you know what's going on here?

**Comment by michellechandra** [comment]
the console says "missingkeymaperror"

![screen shot 2016-07-21 at 10 26 12](https://cloud.githubusercontent.com/assets/5423288/17032348/9fb849c2-4f2d-11e6-96f4-05b714c0189e.png)

https://developers.google.com/maps/documentation/javascript/error-messages

**Comment by michellechandra** [comment]
From Google:

```
The script element that loads the API is missing the required authentication parameter. If you are using the standard Maps JavaScript API, you must use a key parameter with a valid API key. If you are a Premium Plan customer, you must use either a client parameter with your client ID or a key parameter with a valid API key.
```

I believe the map should be using your Google API key?

**Comment by ohasselblad** [comment]
Ah, it's probably because we created that key for cartodb.com domain, so since it's hosted through carto.com now it fails. I think you can just add carto.com as a domain that it can come from when configuring the API Key thingy
