### ISSUE TITLE
create button to download .carto files for example maps

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#367]

**Comment by csobier** [comment]
FYI: You can do this from any selected map on a public profile page....as mentioned in the docs.

![image](https://cloud.githubusercontent.com/assets/13319925/17414234/a27853de-5a52-11e6-870e-07055c59f5bf.png)

**Comment by ohasselblad** [comment]
Yeah, but we want to have one in Map Academy lessons too!
