### ISSUE TITLE
have nav bar only show lessons, not the course

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#377]
The nav looks like this, which is not very useful or informative: 

<img width="517" alt="screen shot 2016-08-06 at 12 54 52" src="https://cloud.githubusercontent.com/assets/1041056/17458043/0fbf441a-5bd5-11e6-8438-876cd9dda8de.png">

**Comment by ohasselblad** [comment]
Related #378

**Comment by carlostallon** [comment]
that UX will be totally changed in the new design, closing then
