### ISSUE TITLE
Have course lists only list lesson titles, not course titles repeatedly

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/academy#378]
I know there are SEO reasons for doing this, but it make the interface less appealing:

<img width="592" alt="screen shot 2016-08-06 at 13 09 25" src="https://cloud.githubusercontent.com/assets/1041056/17458134/6a855266-5bd7-11e6-9f21-0e09a3200eb1.png">

cc @carlostallon @michellechandra

**Comment by carlostallon** [comment]
totally agree!!
