### ISSUE TITLE
Real-time map with CARTO sync tables

### ISSUE THREAD

**Issue by mehak-sachdeva** [CartoDB/academy#395]
Tutorial: https://carto.com/docs/tutorials/realtime_maps_sync/

## To do

- [ ] make new vid?
- [ ] make a product at the end instead of be more docs-oriented
- [ ] add more text to describe processes

**Comment by ohasselblad** [comment]
Cannot use the same dataset because it doesn't agree with our importer: https://github.com/CartoDB/cartodb/issues/6072

**Comment by csobier** [comment]
Closing, dup of Docs issue#1032, which is linked above and contains PR details. You can can edit and/or re-open if there is an additional doc requirement (or video?) needed.
