### ISSUE TITLE
Tips & Tricks Audit 

### ISSUE THREAD

**Issue by asimcox** [CartoDB/academy#414]
Review Tips & Tricks content [https://carto.com/docs/tips-and-tricks/](url) and figure out which content is:
- N/A
- Can be consolidated with other content (i.e guides)
- Can be deprecated
- Can be directly migrated and if so, identify exactly where on the site it will be migrated

^^^ Above decisions should be captured in the content [strategy doc](https://docs.google.com/spreadsheets/d/14tj8aX5F4arYLnbvhTDBY7HHb43J5-e-q1yybSOjoQ0/edit#gid=1343272745)

If out of this exercise, you find content that doesn't belong anywhere else, please use this to determine if this section is necessary and if so, define what the purpose of it will be going forward.

**Comment by csobier** [comment]
Closing. This is a dup task of the deprecation of docs project.
