### ISSUE TITLE
Identify which guides have other guides has pre-reqs

### ISSUE THREAD

**Issue by asimcox** [CartoDB/academy#415]
- [ ] **Identify which guides have other guides has pre-reqs:**
- Certain guides will naturally require other guides a pre-reqs. That won't always be the case,     but please to the exercise of identifying which ones need to be linked to each other.
- [ ] **Identify which Tutorials have guides as pre-reqs**
- [ ] **Identify what the resources are for each Tutorial**
- Part of my is confused --- if we're adding a guide and a pre-req, why would we also link to it as the end of the tutorial as a resource?

Please do this for the Tutorials and the Guides and capture linking decisions in the [content strategy doc.](https://docs.google.com/spreadsheets/d/14tj8aX5F4arYLnbvhTDBY7HHb43J5-e-q1yybSOjoQ0/edit#gid=1343272745)

**Comment by csobier** [comment]
Closing. Duplicate effort of template design and other tasks in progress.
