### ISSUE TITLE
Gather assets/resources for all Tutorials

### ISSUE THREAD

**Issue by asimcox** [CartoDB/academy#416]
Gather resources for each tutorial and link to them with the content strategy doc [https://docs.google.com/spreadsheets/d/14tj8aX5F4arYLnbvhTDBY7HHb43J5-e-q1yybSOjoQ0/edit#gid=1343272745](url)

Resource could include the following:

- Pictures, Gifs
- Videos
- Code snippets
- .Carto file
- Data Download links
- Links to docs/guides, etc

**Comment by csobier** [comment]
Closing. The goal is to increase productivity and save time for everyone. This is a duplicate effort as we've already scoped resources, assigned issues, and provided a template. At this stage, using GitHub to track issues and PR's going forward.
