### ISSUE TITLE
Reformatting Existing Content to fit new "Guide" Content Layout

### ISSUE THREAD

**Issue by asimcox** [CartoDB/academy#418]
- [ ] 1)Assess Existing Map Academy Lessons and determine if they need to be broken down into multiple "Guides" or if a lesson in of itself is (1) "Guide"

- [ ] Assess Existing Tutorials (i.e Christa's current docs tutorials) and determine if they can be migrated "as is" into "Guides".  

- [ ] In both cases, reformat content to fix the context of the "Guide Template" (See @arianaescobar's latest 'Interior Guide Page' wireframe). In some cases we may need to write a little content to properly fill out the template.

**Comment by michellechandra** [comment]
Issue moved to [CartoDB/docs #1053](https://github.com/CartoDB/docs/issues/1053) via [**ZenHub**](https://www.zenhub.com/)
