### ISSUE TITLE
Can you edit boundaries of goejson polygons by drag/drop vertices inside a map? 

### ISSUE THREAD

**Issue by eranchazan** [CartoDB/academy#431]
I have several geosjon polygon feature sets in one map. 

i am wondering if I can edit the geometries of polygons directly in the editor . 

Presumably through the ability to drag vertices around.

Best,

Eran

**Comment by andy-esch** [comment]
Hi @eranchazan, yep, you can edit geometries. For Builder, there's a guide here: https://carto.com/learn/guides/analysis/editing-geometries-with-analysis

For Editor, here's an old video (for the interface before Editor!): https://carto.com/docs/tutorials/adding_geometries
