### ISSUE TITLE
Data not appearing on course intro screens

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/academy#96]
The data layer is not loading here
http://academy.cartodb.com/courses/03-cartodbjs-ground-up.html

I don't know if it's related, but this error appears in the console log: `Uncaught ReferenceError: functionreturn_cdbc_cartodb is not defined`

The data appears normally in the lessons
http://academy.cartodb.com/courses/03-cartodbjs-ground-up/lesson-1.html

**Comment by ohasselblad** [comment]
@matallo , FYI. Should've pinged you before.
Duplicate of CartoDB/cartodb.js#341

**Comment by matallo** [comment]
yeah, waiting for fix on Cartodb.js, thanks! :)

**Comment by ohasselblad** [comment]
@matallo any update on this?

**Comment by matallo** [comment]
it still needs the fix from cartodb.js, which at the moment is not priority, but still in the backlog, sorry @ohasselblad

**Comment by ohasselblad** [comment]
Any progress on this yet?

**Comment by ohasselblad** [comment]
@javisantana here's the issue we discussed earlier
